MusicWebApp/Areas/Music/Controllers/HomepageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicWebApp.Areas.Music.Models;
using System.Web.Script.Serialization;
using MusicWebApp.Models;
using System.Net;
using System.IO;
using Newtonsoft.Json;
using System.Text;
using System.Configuration;

namespace MusicWebApp.Areas.Music.Controllers
{
    public class HomepageController : Controller
    {
        // GET: Music/Homepage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetTop10()
        {
            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music/top10";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            List<MusicWebApp.Models.Music> musics = null;
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                musics = JsonConvert.DeserializeObject<List<MusicWebApp.Models.Music>>(json);
            }

            var data = musics
                .Take(10)
                .Select(a => new IConvertible[]
                {
                    a.Name,
                    a.Id,
                    a.Singer != null ? a.Singer.Fullname : "None",
                    a.Image,
                });

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetMostPopularMusic()
        {
            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music/top10";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            List<MusicWebApp.Models.Music> musics = null;
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                musics = JsonConvert.DeserializeObject<List<MusicWebApp.Models.Music>>(json);
            }

            var data = musics
                .Take(4)
                .Select(a => new IConvertible[]
                {
                    a.Image,
                    a.Id,
                    a.Name + " - " + a.Singer.Fullname,
                });

            return Json(new { success = true, data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetArtistYouMayLike()
        {
            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/singer";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            List<Singer> singers = null;
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                singers = JsonConvert.DeserializeObject<List<Singer>>(json);
            }

            var data = singers
                .OrderBy(a => Guid.NewGuid())
                .Take(10)
                .Select(a => new IConvertible[]
                {
                    a.Image,
                    a.Id,
                    a.Fullname,
                });

            return Json(new { success = true, data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetNewestTracks()
        {
            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music/recent10";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            List<MusicWebApp.Models.Music> musics = null;
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                musics = JsonConvert.DeserializeObject<List<MusicWebApp.Models.Music>>(json);
            }

            var data = musics
                .OrderByDescending(a => a.UploadDate)
                .Take(10)
                .Select(a => new IConvertible[]
                {
                    a.Name,
                    a.Id,
                    a.Singer != null ? a.Singer.Fullname : "None",
                    a.Image,
                });

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetNewestAlbums()
        {
            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/album/recent10";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            List<Album> albums = null;
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                albums = JsonConvert.DeserializeObject<List<Album>>(json);
            }

            var data = albums
                .Take(10)
                .Select(a => new IConvertible[]
                {
                    a.Name,
                    a.Id,
                    a.Singer.Fullname,
                    a.Image,
                });

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetNewestComments()
        {
            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/comments/recent10";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            List<Comment> comments = null;
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                comments = JsonConvert.DeserializeObject<List<Comment>>(json);
            }

            var data = comments
                .Take(10)
                .Select(a => new IConvertible[]
                {
                    a.Music.Name,
                    a.Music.Id,
                    !string.IsNullOrEmpty(a.User.FirstName) && !string.IsNullOrEmpty(a.User.LastName) ? (a.User.FirstName + " " + a.User.LastName) : a.User.Logins.FirstOrDefault().Username,
                    a.User.Avatar,
                    a.Comment1,
                });

            //MusicEntities en = new MusicEntities();
            //var data = en.Comments
            //    .OrderByDescending(a => a.CommentDate)
            //    .Take(10)
            //    .ToList()
            //    .Select(a => new IConvertible[]
            //    {
            //        a.Music.Name,
            //        a.Music.Id,
            //        !string.IsNullOrEmpty(a.User.FirstName) && !string.IsNullOrEmpty(a.User.LastName) ? (a.User.FirstName + " " + a.User.LastName) : a.User.Logins.FirstOrDefault().Username,
            //        a.User.Avatar,
            //        a.Comment1,
            //    });

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }
    }
}

public static class GenresEntities
{
    private static List<Genre> list = null;

    public static List<Genre> InitialModels()
    {
        if (list == null)
        {
            MusicEntities en = new MusicEntities();
            list = en.Genres.ToList();
            list.Insert(0, new Genre { Id = 0, Name = "All" });
        }

        return list;
    }
}

MusicWebApp/Areas/Music/Views/Homepage/Index.cshtml
@{
    ViewBag.Title = "Bring music to your soul";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="col-md-9">
        <h3 style="color: rgb(94, 0, 108)"><b>Most popular music in this week!</b></h3>
        <hr />
        <table id="weekPopularMusic" border="0" class="table-responsive">
            <tr>
                <td colspan="3" class="big-banner">
                    <a href="#" class="week-link">
                        <img src="~/Content/StaticImages/6b49499b796c8ba9e52f1feb83cc6053.gif" data-caption="Placeholder" class="week img-responsive big-image" style="width:100%" />
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="#" class="week-link">
                        <img src="~/Content/StaticImages/6b49499b796c8ba9e52f1feb83cc6053.gif" data-caption="Placeholder" class="week img-responsive" />
                    </a>
                </td>
                <td>
                    <a href="#" class="week-link">
                        <img src="~/Content/StaticImages/6b49499b796c8ba9e52f1feb83cc6053.gif" data-caption="Placeholder" class="week img-responsive" />
                    </a>
                </td>
                <td>
                    <a href="#" class="week-link">
                        <img src="~/Content/StaticImages/6b49499b796c8ba9e52f1feb83cc6053.gif" data-caption="Placeholder" class="week img-responsive" />
                    </a>
                </td>
            </tr>
        </table>
        <hr />

        <h4 style="color: rgb(94, 0, 108)"><b>Artists you may Like!</b></h4>
        <hr />
        <table id="recommendArtists" border="0" class="table-responsive">
            <tbody></tbody>
        </table>
        <hr />

        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4">
                    <table id="newMusic" border="0" class="table-hover table-responsive">
                        <thead>
                            <tr>
                                <td>Newest Music Tracks</td>
                            </tr>
                        </thead>
                    </table>
                </div>
                <div class="col-md-4">
                    <table id="newAlbums" border="0" class="table-hover table-responsive">
                        <thead>
                            <tr>
                                <td>Newest Albums</td>
                            </tr>
                        </thead>
                    </table>
                </div>
                <div class="col-md-4">
                    <table id="newComment" border="0" class="table-hover table-responsive">
                        <thead>
                            <tr>
                                <td>Newest Comments</td>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <table id="tableTop10" border="0" class="table-hover table-responsive">
            <thead>
                <tr>
                    <td>
                        <font color="purple"><b>Top 10 Music Tracks this month</b></font>
                    </td>
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#weekPopularMusic').sliphover({
            caption: 'data-caption'
        });
        $('#recommendArtists').sliphover({
            caption: 'data-caption'
        });

        LoadTableTop10();
        LoadPopularArtist();
        LoadWeekPopular();
        LoadNewestTracks();
        LoadNewestAlbums();
        LoadNewestComments();
    });

    function LoadWeekPopular() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("GetMostPopularMusic", "Homepage")',
            dataType: 'json',
            success: function (data) {
                if (data.success) {
                    var i = 0;
                    $('.week').each(function () {
                        $(this).prop('src', data.data[i][0]);
                        $(this).attr('data-caption', "" + "<h4 style='padding:8px'>" + data.data[i][2] + "</h4>");
                        i++;
                    });
                    var i = 0;
                    $('.week-link').each(function () {
                        $(this).prop('href', "@Url.Action("Index", "PlayMusic")/?musicid=" + data.data[i][1]);
                        i++;
                    });
                }
            }
        });
    }

    function LoadPopularArtist() {
        var table = $('#recommendArtists tbody');
        $.ajax({
            type: 'GET',
            url: '@Url.Action("GetArtistYouMayLike", "Homepage")',
            dataType: 'json',
            success: function (data) {
                if (data.success) {
                    var i = 1;
                    var array = data.data;
                    for (var d in array) {
                        if (i < 2) {
                            table.append("<tr>");
                        }
                        table.append("<td><a href='@Url.Action("SingerAbout", "Singer")/?singerId=" + array[d][1] + "'><img src='" + array[d][0] + "' class='img-responsive' data-caption='" + array[d][2] + "'/></td></a>");
                        if (i > 4) {
                            table.append("</tr>");
                            i = 0;
                        }
                        i++;
                    }
                }
            }
        });
    }

    function LoadTableTop10() {
        $("#tableTop10").dataTable({
            "bServerSide": false,
            "bProcessing": false,
            "bSort": false,
            "bFilter": false,
            "bPaginate": false,
            "sAjaxSource": "@Url.Action("GetTop10", "Homepage")",
            "aoColumnDefs": [
                {
                    "aTargets": [0],
                    "mRender": function (data, type, row) {
                        var track = row[0];
                        var link = row[1];
                        var singer = row[2];
                        var image = row[3];
                        var display = "" +
                            "<div class='row'>" +
                                "<div class='col-md-4'>" +
                                    "<img src='" + image + "' class='img-responsive' />" +
                                "</div>" +
                                "<div class='col-md-8'>" +
                                    "<b><a href='@Url.Action("Index", "PlayMusic")/?musicid=" + link + "'>" + track + "</a></b><br/>" +
                                    singer +
                                "</div>" +
                            "</div>";
                        return display;
                    },
                    "bSortable": false,
                },
            ],
            "bAutoWidth": false,
        });
    }

    function LoadNewestTracks() {
        $("#newMusic").dataTable({
            "bServerSide": false,
            "bProcessing": false,
            "bSort": false,
            "bFilter": false,
            "bPaginate": false,
            "sAjaxSource": "@Url.Action("GetNewestTracks", "Homepage")",
            "aoColumnDefs": [
                {
                    "aTargets": [0],
                    "mRender": function (data, type, row) {
                        var track = row[0];
                        var link = row[1];
                        var singer = row[2];
                        var image = row[3];
                        var display = "" +
                            "<div class='row'>" +
                                "<div class='col-md-4'>" +
                                    "<img src='" + image + "' class='img-responsive' />" +
                                "</div>" +
                                "<div class='col-md-8'>" +
                                    "<b><a href='@Url.Action("Index", "PlayMusic")/?musicid=" + link + "'>" + track + "</a></b><br/>" +
                                    singer +
                                "</div>" +
                            "</div>";
                        return display;
                    },
                    "bSortable": false,
                },
            ],
            "bAutoWidth": false,
        });
    }

    function LoadNewestAlbums() {
        $("#newAlbums").dataTable({
            "bServerSide": false,
            "bProcessing": false,
            "bSort": false,
            "bFilter": false,
            "bPaginate": false,
            "sAjaxSource": "@Url.Action("GetNewestAlbums", "Homepage")",
            "aoColumnDefs": [
                {
                    "aTargets": [0],
                    "mRender": function (data, type, row) {
                        var track = row[0];
                        var link = row[1];
                        var singer = row[2];
                        var image = row[3];
                        var display = "" +
                            "<div class='row'>" +
                                "<div class='col-md-4'>" +
                                    "<img src='" + image + "' class='img-responsive' />" +
                                "</div>" +
                                "<div class='col-md-8'>" +
                                    "<b><a href='@Url.Action("Album", "Album")?albumId=" + link + "'>" + track + "</a></b><br/>" +
                                    singer +
                                "</div>" +
                            "</div>";
                        return display;
                    },
                    "bSortable": false,
                },
            ],
            "bAutoWidth": false,
        });
    }

    function LoadNewestComments() {
        $("#newComment").dataTable({
            "bServerSide": false,
            "bProcessing": false,
            "bFilter": false,
            "bPaginate": false,
            "sAjaxSource": "@Url.Action("GetNewestComments", "Homepage")",
            "bSort": false,
            "aoColumnDefs": [
                {
                    "aTargets": [0],
                    "mRender": function (data, type, row) {
                        var track = row[0];
                        var link = row[1];
                        var username = row[2];
                        var image = row[3];
                        var comment = row[4];
                        var display = "" +
                            "<div class='row'>" +
                                "<div class='col-md-4'>" +
                                    "<img src='" + image + "' class='img-responsive' />" +
                                "</div>" +
                                "<div class='col-md-8'>" +
                                    "<b>" + comment + "</b><br />" +
                                    username + " - <b><a href='@Url.Action("Index", "PlayMusic")/?musicid=" + link + "'>" + track + "</a></b><br/>" +
                                "</div>" +
                            "</div>";
                        return display;
                    },
                    "bSortable": false,
                },
            ],
            "bAutoWidth": false,
        });
    }
</script>