MusicWebApp/Areas/Music/Controllers/MusicTracksController.cs
using MusicWebApp.Areas.Music.Models;
using MusicWebApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MusicWebApp.Areas.Music.Controllers
{
    public class MusicTracksController : Controller
    {
        // GET: Music/MusicTracks
        public ActionResult Index(int id)
        {
            var gen = GenresEntities.InitialModels().FirstOrDefault(a => a.Id == id);
            if (gen == null) gen = GenresEntities.InitialModels().First();
            GenresViewModel models = new GenresViewModel()
            {
                genre = gen,
                list = GenresEntities.InitialModels(),
            };

            return View(models);
        }

        public ActionResult GetGenresMostRecentSongs(JQueryDataTableParamModel param, int genresId)
        {

            List<MusicWebApp.Models.Music> test = null;

            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music/genres/" + genresId;
            if (genresId == 0)
            {
                api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music";
            }

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                test = JsonConvert.DeserializeObject<List<MusicWebApp.Models.Music>>(json);
            }

            var c = test.Count();
            var start = param.iDisplayStart + 1;
            var data = test
                .OrderByDescending(a => a.UploadDate)
                .Skip(param.iDisplayStart)
                .Take(param.iDisplayLength)
                .Select(a => new IConvertible[]
                {
                    start++,
                    a.Name,
                    a.Id,
                    a.Singer.Fullname,
                    a.Image,
                    a.C_View,
                });

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = c,
                iTotalDisplayRecords = c,
                aaData = data
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetGenresMostPopularSongs(JQueryDataTableParamModel param, int genresId)
        {
            List<MusicWebApp.Models.Music> test = null;

            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music/genres/" + genresId;
            if (genresId == 0)
            {
                api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music";
            }

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                test = JsonConvert.DeserializeObject<List<MusicWebApp.Models.Music>>(json);
            }

            var c = test.Count();
            var start = param.iDisplayStart + 1;
            var data = test
                .OrderByDescending(a => a.C_View)
                .Skip(param.iDisplayStart)
                .Take(param.iDisplayLength)
                .Select(a => new IConvertible[]
                {
                    start++,
                    a.Name,
                    a.Id,
                    a.Singer == null ? "" : a.Singer.Fullname,
                    a.Image,
                    a.C_View,
                });


            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = c,
                iTotalDisplayRecords = c,
                aaData = data
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetRandomSongs(int genresId)
        {
            List<MusicWebApp.Models.Music> test = null;

            string api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music/genres/" + genresId;
            if (genresId == 0)
            {
                api = ConfigurationManager.AppSettings["ApiServer"] + "/MusicProject/music";
            }

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(api);
            WebResponse response = request.GetResponse();
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                var json = reader.ReadToEnd();
                test = JsonConvert.DeserializeObject<List<MusicWebApp.Models.Music>>(json);
            }

            var data = test
                .OrderBy(a => Guid.NewGuid())
                .Take(10)
                .Select(a => new IConvertible[]
                {
                    a.Name,
                    a.Id,
                    a.Singer.Fullname,
                    a.Image,
                });

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }
    }

    public class JQueryDataTableParamModel
    {
        /// <summary>
        /// Request sequence number sent by DataTable,
        /// same value must be returned in response
        /// </summary>       
        public string sEcho { get; set; }

        /// <summary>
        /// Text used for filtering
        /// </summary>
        public string sSearch { get; set; }

        /// <summary>
        /// Number of records that should be shown in table
        /// </summary>
        public int iDisplayLength { get; set; }

        /// <summary>
        /// First record that should be shown(used for paging)
        /// </summary>
        public int iDisplayStart { get; set; }

        /// <summary>
        /// Number of columns in table
        /// </summary>
        public int iColumns { get; set; }

        /// <summary>
        /// Number of columns that are used in sorting
        /// </summary>
        public int iSortingCols { get; set; }

        /// <summary>
        /// Comma separated list of column names
        /// </summary>
        public string sColumns { get; set; }

        /// <summary>
        /// Sort column
        /// </summary>
        public int iSortCol_0 { get; set; }

        /// <summary>
        /// Asc or Desc
        /// </summary>
        public string sSortDir_0 { get; set; }
    }
}

MusicWebApp/Areas/Music/Views/MusicTracks/Index.cshtml
@model MusicWebApp.Areas.Music.Models.GenresViewModel

@{
    ViewBag.Title = "Music Tracks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="container row">
        <div class="col-md-9">
            <div class="row">
                <div class="form-group col-md-12">
                    <h2>Genres</h2>
                    <hr />

                    <ul class="list-inline">
                        @foreach (var genre in Model.list)
                        {
                            if (genre.Id == Model.genre.Id)
                            {
                                <li class="list-group-item active"><i class="glyphicon glyphicon-chevron-right"></i> @genre.Name</li>
                            }
                            else
                            {
                                <li class="list-group-item"><i class="glyphicon glyphicon-chevron-right"></i><a href="@Url.Action("Index", "MusicTracks", new { id = genre.Id })"> @genre.Name</a></li>
                            }
                        }
                    </ul>
                </div>
                <div class="form-group col-md-12">
                    <h2>Tracks</h2>
                    <hr />

                    <div class="col-md-12">
                        <ul class="nav nav-pills">
                            <li class="active"><a href="#top" data-toggle="tab">Top Tracks</a></li>
                            <li><a href="#recent" data-toggle="tab">Recent Tracks</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="top">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <table id="mostPop" class="table-hover table-responsive">
                                            <thead>
                                                <tr>
                                                    <td colspan="2"><h4 style="color: rgb(110, 0, 128)"><i class="glyphicon glyphicon-music"></i> Most Popular @ViewBag.Name songs</h4></td>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="recent">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <table id="mostRecent" class="table-hover table-responsive">
                                            <thead>
                                                <tr>
                                                    <td colspan="2"><h4 style="color: rgb(110, 0, 128)"><i class="glyphicon glyphicon-music"></i> Most Popular @ViewBag.Name songs</h4></td>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12" style="float:right">
                    <table id="randomSong" class="table-hover table-responsive">
                        <thead>
                            <tr>
                                <td><font color="purple"><b>Random @Model.genre.Name songs you may like!</b></font></td>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $.fn.dataTable.ext.classes.sPageButton = 'btn btn-primary';
        $.fn.dataTableExt.oStdClasses.sPageButtonActive = "btn-raised";

        LoadMostPopular();
        LoadRecent();
        LoadRandom();
    });

    function LoadRecent() {
        $("#mostRecent").dataTable({
            "bServerSide": true,
            "bProcessing": true,
            "bSort": false,
            "bFilter": false,
            "bLengthChange": false,
            "bInfo" : false,
            "iDisplayLength": 20,
            "sAjaxSource": "@Url.Action("GetGenresMostRecentSongs", "MusicTracks")",
            "fnServerParams": function (aoData) {
                aoData.push(
                    { "name": "genresId", "value": @Model.genre.Id }
                );
            },
            "oLanguage": {
                "oPaginate": {
                    "sInfo": "",
                    "sNext": "<i class='glyphicon glyphicon-step-forward'></i>",
                    "sPrevious": "<i class='glyphicon glyphicon-step-backward'></i>"
                }
            },
            "aoColumnDefs": [
                {
                    "aTargets": [0],
                    "mRender": function (data, type, row)  {
                        return "<h3>" + row[0] + "</h3>";
                    },
                    "bSortable": false,
                    "className": "text-center",
                },
                {
                    "aTargets": [1],
                    "mRender": function (data, type, row) {
                        var track = row[1];
                        var link = row[2];
                        var singer = row[3];
                        var image = row[4];
                        var view = row[5];
                        var display = "" +
                            "<div class='row'>" +
                                "<div class='col-md-2'>" +
                                    "<img src='" + image + "' class='img-responsive' />" +
                                "</div>" +
                                "<div class='col-md-10'>" +
                                    "<span class='pull-right' style='padding-right:16px'>" +
                                        "<i class='glyphicon glyphicon-eye-open'></i> " + view + " " +
                                        "<button class='btn btn-success' onclick='AddToFavorite(" + link + ")'><i class='glyphicon glyphicon-star-empty'></i></button>" +
                                    "</span>" +
                                    "<b><a href='@Url.Action("Index", "PlayMusic")?musicid=" + link + "'>" + track + "</a></b><br/>" +
                                    singer +
                                "</div>" +
                            "</div>";
                        return display;
                    },
                    "bSortable": false,
                },
            ],
            "bAutoWidth": false,
        });
    }

    function LoadMostPopular() {
        $("#mostPop").dataTable({
            "bServerSide": true,
            "bProcessing": true,
            "bSort": false,
            "bFilter": false,
            "bLengthChange": false,
            "bInfo" : false,
            "iDisplayLength": 20,
            "sAjaxSource": "@Url.Action("GetGenresMostPopularSongs", "MusicTracks")",
            "fnServerParams": function (aoData) {
                aoData.push(
                    { "name": "genresId", "value": @Model.genre.Id }
                );
            },
            "oLanguage": {
                "oPaginate": {
                    "sInfo": "",
                    "sNext": "<i class='glyphicon glyphicon-step-forward'></i>",
                    "sPrevious": "<i class='glyphicon glyphicon-step-backward'></i>"
                }
            },
            "aoColumnDefs": [
                {
                    "aTargets": [0],
                    "mRender": function (data, type, row)  {
                        return "<h3>" + row[0] + "</h3>";
                    },
                    "bSortable": false,
                    "className": "text-center",
                },
                {
                    "aTargets": [1],
                    "mRender": function (data, type, row) {
                        var track = row[1];
                        var link = row[2];
                        var singer = row[3];
                        var image = row[4];
                        var view = row[5];
                        var display = "" +
                            "<div class='row'>" +
                                "<div class='col-md-2'>" +
                                    "<img src='" + image + "' class='img-responsive' />" +
                                "</div>" +
                                "<div class='col-md-10'>" +
                                    "<span class='pull-right' style='padding-right:16px'>" +
                                        "<i class='glyphicon glyphicon-eye-open'></i> " + view + " " +
                                        "<button class='btn btn-success' onclick='AddToFavorite(" + link + ")'><i class='glyphicon glyphicon-star-empty'></i></button>" +
                                    "</span>" +
                                    "<b><a href='@Url.Action("Index", "PlayMusic")/?musicid=" + link + "'>" + track + "</a></b><br/>" +
                                    singer +
                                "</div>" +
                            "</div>";
                        return display;
                    },
                    "bSortable": false,
                },
            ],
            "bAutoWidth": false,
        });
    }

    function LoadRandom() {
        $("#randomSong").dataTable({
            "bServerSide": false,
            "bProcessing": false,
            "bSort": false,
            "bFilter": false,
            "bLengthChange": false,
            "bPaginate": false,
            "iDisplayLength": 20,
            "sAjaxSource": "@Url.Action("GetRandomSongs", "MusicTracks")",
            "fnServerParams": function (aoData) {
                aoData.push(
                    { "name": "genresId", "value": @Model.genre.Id }
                );
            },
            "aoColumnDefs": [
                {
                    "aTargets": [0],
                    "mRender": function (data, type, row) {
                        var track = row[0];
                        var link = row[1];
                        var singer = row[2];
                        var image = row[3];
                        var display = "" +
                            "<div class='row'>" +
                                "<div class='col-md-4'>" +
                                    "<img src='" + image + "' class='img-responsive' />" +
                                "</div>" +
                                "<div class='col-md-8'>" +
                                    "<b><a href='@Url.Action("Index", "PlayMusic")/?musicid=" + link + "'>" + track + "</a></b><br/>" +
                                    singer +
                                "</div>" +
                            "</div>";
                        return display;
                    },
                    "bSortable": false,
                },
            ],
            "bAutoWidth": false,
        });
    }
</script>